version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lasha2014
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  spring:
    build:
      context: .
      dockerfile: assets/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  postgres:
